---
language: ruby
rvm:
  - 2.3.4

script:
  - bundle exec jekyll build

deploy:
  provider: s3
  # AWS credentials can be manually re/configured using the travis-ci command
  # line tool:
  #
  #     $ travis setup s3
  #
  bucket: www.scalabridge.org
  skip_cleanup: true
  local_dir: _site
