# Site settings
title: ScalaBridge
email: scalabridge@gmail.com
description: >
  Building an inclusive Scala community with introductory programming workshops for women.
url: "http://www.scalabridge.org"
twitter: scalabridge
github:  scalabridge

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - s3_website.yml
